#!/bin/bash
if [ $# -lt 1 ]; then
  echo -ne "\n"
  echo -ne "USAGE: $0 <pyfiles>\n\n"
  echo -ne "where pyfiles is one or more Python source code files (*.py).\n"
  echo -ne "\n"
  exit 255
fi

SCRIPT=`readlink -f $0`
SCRIPTPATH=`dirname $SCRIPT`
PYFILES=`ls $@ | xargs -I {} readlink -f {}` 

PYTHON=`which python`
which dials.python >/dev/null 2>/dev/null && PYTHON=`which dials.python`

echo -ne "Analyzing...\n"
${PYTHON} -m ${SCRIPTPATH}/pyan/pyan ${PYFILES} -c -e -n --dot > temp.dot
if [ $? -eq 0 ]; then
  echo -ne "Generating layout...\n"
  # "fdp" comes from the graphviz package
  fdp -Txdot -otemp.xdot temp.dot
#  fdp -Gnodesep=100 -Txdot -otemp.xdot temp.dot
#  dot -Txdot -otemp.xdot temp.dot

  echo -ne "Visualizing...\n"
  # -n = filter off (input already in xdot format)
  python -m ${SCRIPTPATH}/xdot/xdot -n temp.xdot
fi

